$version: '3'  # Utilisez une version de Compose compatible, comme 3

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: devops
    networks:
      - mynetwork

  spring-app:
    build:
      context: .  # Indique le répertoire où se trouve le Dockerfile de votre application Spring Boot
      dockerfile: Dockerfile  # Le nom du fichier Dockerfile pour votre application
    ports:
      - "8086:8086"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/devops
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:  # Définissez ici votre mot de passe pour la base de données
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - mynetwork

networks:
  mynetwork:
