version: "3.3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE= produitdb
      - MYSQL_ALLOW_EMPTY_PASSWORD= yes
    ports:
      - "3306:3306"
  app:
    depends_on:
      - mysqldb
    image: 161jmt3600/produit
    container_name: projetproduit
    restart: unless-stopped
    ports:
      - "8089:8089"
