version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: devops
    networks:
      - mynetwork

  spring-app:
    image: nidhalboughanmi/my-java-app:1.0
    ports:
      - "8086:8086"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/devops?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - mynetwork

networks:
  mynetwork: