version: '3.8'
services:
  api:
    image: mahdizgolli/devopsproject
    container_name: devopsproject
    ports:
      - '8082:8082'
    depends_on:
      - db
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/devops?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=devops
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=devops
      - MYSQL_ROOT_PASSWORD=devops
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
